### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by Hamtaro19** [MegaMoo77/favorites-search#6]
Hello there, guys. I've been having a bit of an inconvenience for the past 6 months or so. See, previously on another computer whenever I used the tool, and clicked on an image, it would direct me to that image. But ever since I switched to another computer, whenever I click an image, it takes me to this page where it says "Page Not Found" where it proceeds to say this:

Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

Back to our site

If this is your site, and you weren't expecting a 404 for this path, please visit Netlify's ["page not found" support guide](https://answers.netlify.com/t/support-guide-i-ve-deployed-my-site-but-i-still-see-page-not-found/125?utm_source=404page&utm_campaign=community_tracking) for troubleshooting tips.

![What the Heck](https://github.com/MegaMoo77/favorites-search/assets/73994779/c2a52813-444b-4193-aca9-e2c4d3f365dc)

Now, instead, I have to right click on the image and open it in a new tab. It's not a big deal honestly, but it's quite a bit annoying. I've assumed maybe this had to do w/ my web browser or somethin', but I can't seem to fix the issue even if I set everything back to default. I use Firefox btw. Thnx.

**Comment by MegaMoo77** [comment]
Interesting, that's a new one. Can you paste the link it tries to open when you click on an image?

**Comment by Hamtaro19** [comment]
Yes, ofc! Here's the link of the image I provided in the screenshot as well as a video. It does this literally for every picture whether it's a stilled pic, GIF, or video.

Original link to the Image: https://rule34.xxx/index.php?page=post&s=view&id=6214593

The result I get from the Image: https://inspiring-benz-219a0a.netlify.app/index.php?page=post&s=view&id=6214593

Original link to the Video: https://rule34.xxx/index.php?page=post&s=view&id=8388581

The result I get from the Video: https://inspiring-benz-219a0a.netlify.app/index.php?page=post&s=view&id=8388581

![Proof1](https://github.com/MegaMoo77/favorites-search/assets/73994779/cce58178-8086-4898-bece-d7ba9c46b2c4)

![Proof2](https://github.com/MegaMoo77/favorites-search/assets/73994779/c2c5498e-0a0c-4052-ad24-76db74ade619)

**Comment by Hamtaro19** [comment]
Hey, I just made a huge discovery. I tried to replicate this on Chrome, and in chrome it seems to...work??? I tried to do it while I'm logged in and out and it worked both ways...I am speechless. Then I guess it's definitely a Firefox issue then. Idk what to do now lol but this is HUGE!!! I switched from Chrome to FF a while ago, but I never tried to use Chrome on this computer.

**Comment by ibigfire** [comment]
I am also having this issue, for what it's worth.  Also on Firefox.

**Comment by MegaMoo77** [comment]
Sorry for the delayed response. I tried replicating this, but I can't seem to. I tried with the same id and search you gave me, and it does not have the issue on Firefox, Chrome, or Opera. That link you said it's taking you to is indeed wrong, but I'm not sure what's generating that. Maybe your browser is trying to overwrite some behavior to avoid cross domain posting?

I want to try seeing the html that gets generated for you. Can you recreate the state from your image, right click and "Save As", then make sure to save it as "Webpage, single file" (.mhtml)? This will let me see where that broken link is located. It would also help if you showed what was displayed in the very bottom left of your browser when you hover over the image (should preview the link).

**Comment by ibigfire** [comment]
No worries!  I found some interesting behaviour that might help as well.  If I just left click on the thumbnail image then I get the behaviour mentioned above.  But if I middle click on it so it opens in a new tab then it works fine and redirects to rule34 as expected.  Also if I left click on the "Original Image" text below the thumbnail it works fine, but that just opens up in a new tab anyway regardless of if I left click or middle click.

But here, I've attached the html file as well as the css file, there doesn't seem to be a .mhtml option when saving in Firefox.  I changed them both to .txt files though because github doesn't support html or css filetypes.  The link preview when hovering over the thumbnail is `https://rule34.xxx/index.php?page=post&s=view&id=6932149` and the link preview when hovering over the "Original Image" text below the thumbnail is `https://inspiring-benz-219a0a.netlify.app/showOriginalRedirect.html?id=6932149`

I hope that helps!
[Page Not Found.txt](https://github.com/MegaMoo77/favorites-search/files/12517049/Page.Not.Found.txt)
[css.txt](https://github.com/MegaMoo77/favorites-search/files/12517048/css.txt)

**Comment by MegaMoo77** [comment]
Thank you for that information! Clicking the image was always meant to open a new tab, so the fact that it wasn't doing that for you was the hint that let me figure out the issue. Looks like it was due to Firefox handling onclick elements differently. I just pushed a fix, hopefully it works now!

**Comment by ibigfire** [comment]
I just checked, and it works a treat now.  Glad the info I provided helped!  Thanks for fixing it up and for providing such a useful tool in the first place, you rock.  All the best to ya!
